version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "/application_stack_data/redis:/data"
  
  web_blue:
    image: localhost:5000/flask-redis-app:latest
    container_name: flask_app_blue
    ports:
      - "8000:8000"
    depends_on:
      - redis
